// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FluidNexus.proto

package net.fluidnexus.FluidNexus;

public final class FluidNexusProtos {
  private FluidNexusProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public static final class FluidNexusHashes extends
      com.google.protobuf.GeneratedMessageLite {
    // Use FluidNexusHashes.newBuilder() to construct.
    private FluidNexusHashes() {
      initFields();
    }
    private FluidNexusHashes(boolean noInit) {}
    
    private static final FluidNexusHashes defaultInstance;
    public static FluidNexusHashes getDefaultInstance() {
      return defaultInstance;
    }
    
    public FluidNexusHashes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated string message_hash = 1;
    public static final int MESSAGE_HASH_FIELD_NUMBER = 1;
    private java.util.List<java.lang.String> messageHash_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getMessageHashList() {
      return messageHash_;
    }
    public int getMessageHashCount() { return messageHash_.size(); }
    public java.lang.String getMessageHash(int index) {
      return messageHash_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (java.lang.String element : getMessageHashList()) {
        output.writeString(1, element);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (java.lang.String element : getMessageHashList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getMessageHashList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes, Builder> {
      private net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes result;
      
      // Construct using net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes();
        return builder;
      }
      
      protected net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes getDefaultInstanceForType() {
        return net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.messageHash_ != java.util.Collections.EMPTY_LIST) {
          result.messageHash_ =
            java.util.Collections.unmodifiableList(result.messageHash_);
        }
        net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes other) {
        if (other == net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusHashes.getDefaultInstance()) return this;
        if (!other.messageHash_.isEmpty()) {
          if (result.messageHash_.isEmpty()) {
            result.messageHash_ = new java.util.ArrayList<java.lang.String>();
          }
          result.messageHash_.addAll(other.messageHash_);
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              addMessageHash(input.readString());
              break;
            }
          }
        }
      }
      
      
      // repeated string message_hash = 1;
      public java.util.List<java.lang.String> getMessageHashList() {
        return java.util.Collections.unmodifiableList(result.messageHash_);
      }
      public int getMessageHashCount() {
        return result.getMessageHashCount();
      }
      public java.lang.String getMessageHash(int index) {
        return result.getMessageHash(index);
      }
      public Builder setMessageHash(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.messageHash_.set(index, value);
        return this;
      }
      public Builder addMessageHash(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.messageHash_.isEmpty()) {
          result.messageHash_ = new java.util.ArrayList<java.lang.String>();
        }
        result.messageHash_.add(value);
        return this;
      }
      public Builder addAllMessageHash(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.messageHash_.isEmpty()) {
          result.messageHash_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.messageHash_);
        return this;
      }
      public Builder clearMessageHash() {
        result.messageHash_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:FluidNexus.FluidNexusHashes)
    }
    
    static {
      defaultInstance = new FluidNexusHashes(true);
      net.fluidnexus.FluidNexus.FluidNexusProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:FluidNexus.FluidNexusHashes)
  }
  
  public static final class FluidNexusMessage extends
      com.google.protobuf.GeneratedMessageLite {
    // Use FluidNexusMessage.newBuilder() to construct.
    private FluidNexusMessage() {
      initFields();
    }
    private FluidNexusMessage(boolean noInit) {}
    
    private static final FluidNexusMessage defaultInstance;
    public static FluidNexusMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public FluidNexusMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum MessageType
        implements com.google.protobuf.Internal.EnumLite {
      TEXT(0, 0),
      IMAGE(1, 1),
      AUDIO(2, 2),
      VIDEO(3, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return TEXT;
          case 1: return IMAGE;
          case 2: return AUDIO;
          case 3: return VIDEO;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number)
      ;        }
            };
      
      private final int index;
      private final int value;
      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:FluidNexus.FluidNexusMessage.MessageType)
    }
    
    // optional string message_title = 1;
    public static final int MESSAGE_TITLE_FIELD_NUMBER = 1;
    private boolean hasMessageTitle;
    private java.lang.String messageTitle_ = "";
    public boolean hasMessageTitle() { return hasMessageTitle; }
    public java.lang.String getMessageTitle() { return messageTitle_; }
    
    // optional string message_content = 2;
    public static final int MESSAGE_CONTENT_FIELD_NUMBER = 2;
    private boolean hasMessageContent;
    private java.lang.String messageContent_ = "";
    public boolean hasMessageContent() { return hasMessageContent; }
    public java.lang.String getMessageContent() { return messageContent_; }
    
    // optional float message_timestamp = 3;
    public static final int MESSAGE_TIMESTAMP_FIELD_NUMBER = 3;
    private boolean hasMessageTimestamp;
    private float messageTimestamp_ = 0F;
    public boolean hasMessageTimestamp() { return hasMessageTimestamp; }
    public float getMessageTimestamp() { return messageTimestamp_; }
    
    // optional string message_hash = 4;
    public static final int MESSAGE_HASH_FIELD_NUMBER = 4;
    private boolean hasMessageHash;
    private java.lang.String messageHash_ = "";
    public boolean hasMessageHash() { return hasMessageHash; }
    public java.lang.String getMessageHash() { return messageHash_; }
    
    // optional string message_source = 5;
    public static final int MESSAGE_SOURCE_FIELD_NUMBER = 5;
    private boolean hasMessageSource;
    private java.lang.String messageSource_ = "";
    public boolean hasMessageSource() { return hasMessageSource; }
    public java.lang.String getMessageSource() { return messageSource_; }
    
    // optional bool message_mine = 6;
    public static final int MESSAGE_MINE_FIELD_NUMBER = 6;
    private boolean hasMessageMine;
    private boolean messageMine_ = false;
    public boolean hasMessageMine() { return hasMessageMine; }
    public boolean getMessageMine() { return messageMine_; }
    
    // optional .FluidNexus.FluidNexusMessage.MessageType message_type = 7;
    public static final int MESSAGE_TYPE_FIELD_NUMBER = 7;
    private boolean hasMessageType;
    private net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.MessageType messageType_;
    public boolean hasMessageType() { return hasMessageType; }
    public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.MessageType getMessageType() { return messageType_; }
    
    // optional bytes message_attachment = 8;
    public static final int MESSAGE_ATTACHMENT_FIELD_NUMBER = 8;
    private boolean hasMessageAttachment;
    private com.google.protobuf.ByteString messageAttachment_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMessageAttachment() { return hasMessageAttachment; }
    public com.google.protobuf.ByteString getMessageAttachment() { return messageAttachment_; }
    
    private void initFields() {
      messageType_ = net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.MessageType.TEXT;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMessageTitle()) {
        output.writeString(1, getMessageTitle());
      }
      if (hasMessageContent()) {
        output.writeString(2, getMessageContent());
      }
      if (hasMessageTimestamp()) {
        output.writeFloat(3, getMessageTimestamp());
      }
      if (hasMessageHash()) {
        output.writeString(4, getMessageHash());
      }
      if (hasMessageSource()) {
        output.writeString(5, getMessageSource());
      }
      if (hasMessageMine()) {
        output.writeBool(6, getMessageMine());
      }
      if (hasMessageType()) {
        output.writeEnum(7, getMessageType().getNumber());
      }
      if (hasMessageAttachment()) {
        output.writeBytes(8, getMessageAttachment());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMessageTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getMessageTitle());
      }
      if (hasMessageContent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMessageContent());
      }
      if (hasMessageTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, getMessageTimestamp());
      }
      if (hasMessageHash()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getMessageHash());
      }
      if (hasMessageSource()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getMessageSource());
      }
      if (hasMessageMine()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, getMessageMine());
      }
      if (hasMessageType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, getMessageType().getNumber());
      }
      if (hasMessageAttachment()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getMessageAttachment());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage, Builder> {
      private net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage result;
      
      // Construct using net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage();
        return builder;
      }
      
      protected net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage getDefaultInstanceForType() {
        return net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage other) {
        if (other == net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.getDefaultInstance()) return this;
        if (other.hasMessageTitle()) {
          setMessageTitle(other.getMessageTitle());
        }
        if (other.hasMessageContent()) {
          setMessageContent(other.getMessageContent());
        }
        if (other.hasMessageTimestamp()) {
          setMessageTimestamp(other.getMessageTimestamp());
        }
        if (other.hasMessageHash()) {
          setMessageHash(other.getMessageHash());
        }
        if (other.hasMessageSource()) {
          setMessageSource(other.getMessageSource());
        }
        if (other.hasMessageMine()) {
          setMessageMine(other.getMessageMine());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasMessageAttachment()) {
          setMessageAttachment(other.getMessageAttachment());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              setMessageTitle(input.readString());
              break;
            }
            case 18: {
              setMessageContent(input.readString());
              break;
            }
            case 29: {
              setMessageTimestamp(input.readFloat());
              break;
            }
            case 34: {
              setMessageHash(input.readString());
              break;
            }
            case 42: {
              setMessageSource(input.readString());
              break;
            }
            case 48: {
              setMessageMine(input.readBool());
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.MessageType value = net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.MessageType.valueOf(rawValue);
              if (value != null) {
                setMessageType(value);
              }
              break;
            }
            case 66: {
              setMessageAttachment(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional string message_title = 1;
      public boolean hasMessageTitle() {
        return result.hasMessageTitle();
      }
      public java.lang.String getMessageTitle() {
        return result.getMessageTitle();
      }
      public Builder setMessageTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessageTitle = true;
        result.messageTitle_ = value;
        return this;
      }
      public Builder clearMessageTitle() {
        result.hasMessageTitle = false;
        result.messageTitle_ = getDefaultInstance().getMessageTitle();
        return this;
      }
      
      // optional string message_content = 2;
      public boolean hasMessageContent() {
        return result.hasMessageContent();
      }
      public java.lang.String getMessageContent() {
        return result.getMessageContent();
      }
      public Builder setMessageContent(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessageContent = true;
        result.messageContent_ = value;
        return this;
      }
      public Builder clearMessageContent() {
        result.hasMessageContent = false;
        result.messageContent_ = getDefaultInstance().getMessageContent();
        return this;
      }
      
      // optional float message_timestamp = 3;
      public boolean hasMessageTimestamp() {
        return result.hasMessageTimestamp();
      }
      public float getMessageTimestamp() {
        return result.getMessageTimestamp();
      }
      public Builder setMessageTimestamp(float value) {
        result.hasMessageTimestamp = true;
        result.messageTimestamp_ = value;
        return this;
      }
      public Builder clearMessageTimestamp() {
        result.hasMessageTimestamp = false;
        result.messageTimestamp_ = 0F;
        return this;
      }
      
      // optional string message_hash = 4;
      public boolean hasMessageHash() {
        return result.hasMessageHash();
      }
      public java.lang.String getMessageHash() {
        return result.getMessageHash();
      }
      public Builder setMessageHash(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessageHash = true;
        result.messageHash_ = value;
        return this;
      }
      public Builder clearMessageHash() {
        result.hasMessageHash = false;
        result.messageHash_ = getDefaultInstance().getMessageHash();
        return this;
      }
      
      // optional string message_source = 5;
      public boolean hasMessageSource() {
        return result.hasMessageSource();
      }
      public java.lang.String getMessageSource() {
        return result.getMessageSource();
      }
      public Builder setMessageSource(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessageSource = true;
        result.messageSource_ = value;
        return this;
      }
      public Builder clearMessageSource() {
        result.hasMessageSource = false;
        result.messageSource_ = getDefaultInstance().getMessageSource();
        return this;
      }
      
      // optional bool message_mine = 6;
      public boolean hasMessageMine() {
        return result.hasMessageMine();
      }
      public boolean getMessageMine() {
        return result.getMessageMine();
      }
      public Builder setMessageMine(boolean value) {
        result.hasMessageMine = true;
        result.messageMine_ = value;
        return this;
      }
      public Builder clearMessageMine() {
        result.hasMessageMine = false;
        result.messageMine_ = false;
        return this;
      }
      
      // optional .FluidNexus.FluidNexusMessage.MessageType message_type = 7;
      public boolean hasMessageType() {
        return result.hasMessageType();
      }
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.MessageType getMessageType() {
        return result.getMessageType();
      }
      public Builder setMessageType(net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMessageType = true;
        result.messageType_ = value;
        return this;
      }
      public Builder clearMessageType() {
        result.hasMessageType = false;
        result.messageType_ = net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.MessageType.TEXT;
        return this;
      }
      
      // optional bytes message_attachment = 8;
      public boolean hasMessageAttachment() {
        return result.hasMessageAttachment();
      }
      public com.google.protobuf.ByteString getMessageAttachment() {
        return result.getMessageAttachment();
      }
      public Builder setMessageAttachment(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessageAttachment = true;
        result.messageAttachment_ = value;
        return this;
      }
      public Builder clearMessageAttachment() {
        result.hasMessageAttachment = false;
        result.messageAttachment_ = getDefaultInstance().getMessageAttachment();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:FluidNexus.FluidNexusMessage)
    }
    
    static {
      defaultInstance = new FluidNexusMessage(true);
      net.fluidnexus.FluidNexus.FluidNexusProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:FluidNexus.FluidNexusMessage)
  }
  
  public static final class FluidNexusMessages extends
      com.google.protobuf.GeneratedMessageLite {
    // Use FluidNexusMessages.newBuilder() to construct.
    private FluidNexusMessages() {
      initFields();
    }
    private FluidNexusMessages(boolean noInit) {}
    
    private static final FluidNexusMessages defaultInstance;
    public static FluidNexusMessages getDefaultInstance() {
      return defaultInstance;
    }
    
    public FluidNexusMessages getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .FluidNexus.FluidNexusMessage message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.util.List<net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage> message_ =
      java.util.Collections.emptyList();
    public java.util.List<net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage> getMessageList() {
      return message_;
    }
    public int getMessageCount() { return message_.size(); }
    public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage getMessage(int index) {
      return message_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage element : getMessageList()) {
        output.writeMessage(1, element);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage element : getMessageList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages, Builder> {
      private net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages result;
      
      // Construct using net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages();
        return builder;
      }
      
      protected net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages getDefaultInstanceForType() {
        return net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.message_ != java.util.Collections.EMPTY_LIST) {
          result.message_ =
            java.util.Collections.unmodifiableList(result.message_);
        }
        net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages other) {
        if (other == net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessages.getDefaultInstance()) return this;
        if (!other.message_.isEmpty()) {
          if (result.message_.isEmpty()) {
            result.message_ = new java.util.ArrayList<net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage>();
          }
          result.message_.addAll(other.message_);
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.Builder subBuilder = net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .FluidNexus.FluidNexusMessage message = 1;
      public java.util.List<net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage> getMessageList() {
        return java.util.Collections.unmodifiableList(result.message_);
      }
      public int getMessageCount() {
        return result.getMessageCount();
      }
      public net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage getMessage(int index) {
        return result.getMessage(index);
      }
      public Builder setMessage(int index, net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.message_.set(index, value);
        return this;
      }
      public Builder setMessage(int index, net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.Builder builderForValue) {
        result.message_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMessage(net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.message_.isEmpty()) {
          result.message_ = new java.util.ArrayList<net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage>();
        }
        result.message_.add(value);
        return this;
      }
      public Builder addMessage(net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage.Builder builderForValue) {
        if (result.message_.isEmpty()) {
          result.message_ = new java.util.ArrayList<net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage>();
        }
        result.message_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMessage(
          java.lang.Iterable<? extends net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage> values) {
        if (result.message_.isEmpty()) {
          result.message_ = new java.util.ArrayList<net.fluidnexus.FluidNexus.FluidNexusProtos.FluidNexusMessage>();
        }
        super.addAll(values, result.message_);
        return this;
      }
      public Builder clearMessage() {
        result.message_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:FluidNexus.FluidNexusMessages)
    }
    
    static {
      defaultInstance = new FluidNexusMessages(true);
      net.fluidnexus.FluidNexus.FluidNexusProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:FluidNexus.FluidNexusMessages)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
