/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.zeitkunst.FluidNexus;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int fluid_nexus_help_icon=0x7f020000;
        public static final int fluid_nexus_icon=0x7f020001;
        public static final int menu_add=0x7f020002;
        public static final int menu_all=0x7f020003;
        public static final int menu_all_list_icon=0x7f020004;
        public static final int menu_delete=0x7f020005;
        public static final int menu_help=0x7f020006;
        public static final int menu_settings=0x7f020007;
        public static final int menu_view=0x7f020008;
        public static final int menu_view_list_icon=0x7f020009;
    }
    public static final class id {
        public static final int discard_message_button=0x7f05000f;
        public static final int help_button_layout=0x7f050008;
        public static final int help_icon=0x7f050004;
        public static final int help_ok_button=0x7f050009;
        public static final int help_text=0x7f050007;
        public static final int help_text_layout=0x7f050005;
        public static final int list_item_layout=0x7f050015;
        public static final int message_edit=0x7f050010;
        public static final int message_list_data=0x7f050018;
        public static final int message_list_header_relative=0x7f050013;
        public static final int message_list_header_text=0x7f050012;
        public static final int message_list_item=0x7f050017;
        public static final int message_list_item_icon=0x7f050016;
        public static final int message_text=0x7f05000d;
        public static final int save_message_button=0x7f05000e;
        public static final int settings_cancel_button=0x7f050022;
        public static final int settings_save_button=0x7f050021;
        public static final int show_messages_check=0x7f050020;
        public static final int title_edit=0x7f05000c;
        public static final int title_text=0x7f05000b;
        public static final int top_relative_layout=0x7f050001;
        public static final int transparent_panel=0x7f050014;
        public static final int view_message_back=0x7f05001f;
        public static final int view_message_data=0x7f05001e;
        public static final int view_message_data_title=0x7f05001c;
        public static final int view_message_title=0x7f05001b;
        public static final int view_message_title_string=0x7f05001a;
        public static final int widget27=0x7f050000;
        public static final int widget28=0x7f05001d;
        public static final int widget29=0x7f050002;
        public static final int widget30=0x7f050003;
        public static final int widget33=0x7f050019;
        public static final int widget39=0x7f05000a;
        public static final int widget40=0x7f050011;
        public static final int widget65=0x7f050006;
    }
    public static final class layout {
        public static final int help=0x7f030000;
        public static final int main=0x7f030001;
        public static final int message_edit=0x7f030002;
        public static final int message_list=0x7f030003;
        public static final int message_list_header=0x7f030004;
        public static final int message_list_item=0x7f030005;
        public static final int message_view=0x7f030006;
        public static final int settings=0x7f030007;
    }
    public static final class string {
        public static final int app_name=0x7f040006;
        public static final int discard_message_button=0x7f040016;
        public static final int help_text=0x7f04001a;
        public static final int help_title=0x7f040009;
        public static final int language_text=0x7f040003;
        public static final int menu_add_message=0x7f04000e;
        public static final int menu_delete=0x7f040011;
        public static final int menu_help=0x7f040013;
        public static final int menu_settings=0x7f040012;
        public static final int menu_view_all=0x7f04000f;
        public static final int menu_view_outgoing=0x7f040010;
        public static final int message_add_outgoing_title=0x7f04000a;
        public static final int message_list_header_text_all=0x7f04000c;
        public static final int message_list_header_text_outgoing=0x7f04000d;
        public static final int message_text=0x7f040004;
        public static final int message_view_outgoing_title=0x7f04000b;
        public static final int message_view_title=0x7f040008;
        public static final int ok_button=0x7f040019;
        public static final int save_message_button=0x7f040015;
        public static final int settings_cancel_button=0x7f040018;
        public static final int settings_save_button=0x7f040017;
        public static final int settings_title=0x7f040007;
        public static final int show_messages_text=0x7f040000;
        public static final int title_text=0x7f040005;
        public static final int view_message_back=0x7f040014;
        public static final int view_message_data_string=0x7f040002;
        public static final int view_message_title_string=0x7f040001;
    }
}
