/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.zeitkunst.FluidNexus;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int fluid_nexus_icon=0x7f020000;
    }
    public static final class id {
        public static final int language_spinner=0x7f05000e;
        public static final int message=0x7f050004;
        public static final int message_list_data=0x7f050008;
        public static final int message_list_item=0x7f050007;
        public static final int message_list_item_icon=0x7f050006;
        public static final int message_text=0x7f050003;
        public static final int show_messages_check=0x7f05000f;
        public static final int title=0x7f050002;
        public static final int title_text=0x7f050001;
        public static final int title_text_view=0x7f05000d;
        public static final int view_message_data=0x7f05000c;
        public static final int view_message_data_title=0x7f05000b;
        public static final int view_message_title=0x7f05000a;
        public static final int view_message_title_string=0x7f050009;
        public static final int widget27=0x7f050005;
        public static final int widget28=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int message_edit=0x7f030001;
        public static final int message_list=0x7f030002;
        public static final int message_list_item=0x7f030003;
        public static final int message_view=0x7f030004;
        public static final int settings=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f040006;
        public static final int language_text=0x7f040003;
        public static final int menu_add_message=0x7f040008;
        public static final int menu_settings=0x7f04000a;
        public static final int menu_view_outgoing=0x7f040009;
        public static final int message_text=0x7f040004;
        public static final int settings_title=0x7f040007;
        public static final int show_messages_text=0x7f040000;
        public static final int title_text=0x7f040005;
        public static final int view_message_data_title=0x7f040002;
        public static final int view_message_title_string=0x7f040001;
    }
}
